server:
  port: 10010
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
#配置路由
zuul:
  routes:
    user-server: /usr-server/**
   # hehe:
      #path: /user-server/**
     #url: http://127.0.0.1:8081
      #serviceId: user-server
